"""adiciona tabelas de objetos e categorias

Revision ID: 288bcc6a1d89
Revises: c34d92f76656
Create Date: 2026-10-09 17:16:13.509124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288bcc6a1d89'
down_revision = 'c34d92f76656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('objeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('local', sa.String(length=100), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devolucoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_devolucao', sa.DateTime(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('objeto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['objeto_id'], ['objeto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('objeto_id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_nome'), ['nome'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_nome'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('devolucoes')
    op.drop_table('objeto')
    op.drop_table('categoria')
    # ### end Alembic commands ###
