"""adicionando os dados de quem encontrou

Revision ID: 525d39b1d1f5
Revises: 288bcc6a1d89
Create Date: 2026-10-09 17:28:30.993703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525d39b1d1f5'
down_revision = '288bcc6a1d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objeto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_objeto', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('nome_encontrou', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('matricula', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('turma', sa.String(length=50), nullable=False))
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objeto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('turma')
        batch_op.drop_column('matricula')
        batch_op.drop_column('nome_encontrou')
        batch_op.drop_column('nome_objeto')

    # ### end Alembic commands ###
